modLoader="javafml"
loaderVersion="[4,)"
license="ARR"
issueTrackerURL="https://github.com/cortex/voxy/issues"

[[mods]]
modId="voxy"
version="${version}"
displayName="Neo-Voxy"
displayTest="IGNORE_SERVER_VERSION"
logoFile="assets/voxy/icon.png"
authors="Cortex"
description='''
Far distance rendering mod utilizing LoDs for massive render distances.
'''

[[dependencies.voxy]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.voxy]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.voxy]]
modId="sodium"
type="required"
versionRange="[0.6.0,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="voxy.mixins.json"

[[mixins]]
config="voxy-common.mixins.json"
